#!/bin/bash 

# Include private details (such as passwords)
source ./config/private_details/.env

# ----------------------------------- #
# --- BEGIN CONFIGURATION SECTION --- #
# ----------------------------------- #

# IMPORTANT: Please put your custom SSH keys in ./private_details/container_id_rsa and ./private_details/container_id_rsa.pub
# If this is not provided, this will default to your host's SSH keys 

# Set username and password inside the container
# IMPORTANT: change default password in ./private_details/.env 
name="dylan"
password="$password"

# Host name (corresponding to file system folder Users/host_name for Windows, or /home/host_name for Linux or MacOS)
host_name="dylan"

# Set to either "docker" or "podman" (if unsure, use "docker")
container_manager="podman"

# Name of the container (set to any meaningful project name)
container_name="container_name"

# Name of the terminal, purely cosmetic (i.e. terminal looks like name@terminal-name:/)
terminal_name="terminal-name"

# Git credentials 
github_username="DylanMoss1"
github_email="dylan.moss2001@gmail.com"

# Custom docker/podman run commands
custom_args=""

# --------------------------------- #
# --- END CONFIGURATION SECTION --- #
# --------------------------------- #

# Path to _host_ folder to mount file from 
mount_onto=$(dirname "$(pwd)")

# Path to _container_ folder to mount files onto 
work_directory=/home/$name/"$(basename "$mount_onto")"
